# Generated by Django 6.1.1 on 2026-09-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employee_bank_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_days_per_month', models.PositiveSmallIntegerField(default=2)),
                ('excess_deduction_per_day', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='payslip',
            name='leave_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='leave_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
